app/urls.py
from django.conf.urls import patterns, url

from app import views

urlpatterns = patterns('',
                       url(r'^submit_file$', views.submit_file, name='submit_file'),
                       url(r'^submit_text$', views.submit_text, name='submit_text'),
                       url(r'^submit_email$', views.submit_email, name='submit_email'),
                       url(r'^verify_email$', views.verify_email, name='verify_email'),
                       url(r'^unsubscribe_project', views.unsubscribe_project, name='unsubscribe_project'),
                       url(r'^unsubscribe', views.unsubscribe, name='unsubscribe'),
                       url(r'^support', views.support, name='support'),
                       url(r'^faq', views.faq, name='faq'),
                       url(r'^$', views.index, name='index'),

                       # GUI testing purpose routes,
                       url(r'^devtest_verify_email$', views.devtest_verify_email, name='devtest_verify_email'),
                       url(r'^devtest_unsubscribe$', views.devtest_unsubscribe, name='devtest_unsubscribe'),
                       url(r'^devtest_unsubscribe_project$', views.devtest_unsubscribe_project, name='devtest_unsubscribe_project')
)

libreeze/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'libreeze.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),


    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('app.urls', namespace='app')),
)

app/templates/app/email-verification-pending.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

{% load staticfiles %}

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<meta name="description" content="">
	<meta name="author" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

	<!-- Google web fonts -->
	<link rel='stylesheet' href="http://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700" />
	<link rel='stylesheet' href="//fonts.googleapis.com/css?family=Raleway:400,300,600" type="text/css" />

	<!-- CSS styles -->
	<link rel="stylesheet" href="{% static 'app/css/lb-main.css' %}" />

	<script src="{% static 'app/js/vendor/modernizr-2.6.2.min.js' %}"></script>
</head>

<body>
	<!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

	<div class="container">
		<div class="row">
			<header>libreeze.net</header>
			<br/>
			<br/>
			<br/>
			<nav></nav>
		</div>
		<div class="row">
			<div class="column">
				<!-- MAIN CONTENT GOES HERE -->
			</div>
		</div>
	</div>

	<br/>
	<br/>
	<br/>

	<footer class="text-center">&copy;libreeze 2015</footer>

	<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
	<script>
		(function (b, o, i, l, e, r) {
			b.GoogleAnalyticsObject = l;
			b[l] || (b[l] =
				function () {
					(b[l].q = b[l].q || []).push(arguments)
				});
			b[l].l = +new Date;
			e = o.createElement(i);
			r = o.getElementsByTagName(i)[0];
			e.src = '//www.google-analytics.com/analytics.js';
			r.parentNode.insertBefore(e, r)
		}(window, document, 'script', 'ga'));
		ga('create', 'UA-XXXXX-X');
		ga('send', 'pageview');
	</script>
</body>

</html>

app/templates/app/email-verification.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

{% load staticfiles %}

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Libreeze</title>
	<meta name="description" content="">
	<meta name="author" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Favicons and apple-touch-icon.png -->
	<link rel="apple-touch-icon" sizes="57x57" href="{% static 'app/img/favicon/apple-touch-icon-57x57.png' %}">
	<link rel="apple-touch-icon" sizes="60x60" href="{% static 'app/img/favicon/apple-touch-icon-60x60.png' %}">
	<link rel="apple-touch-icon" sizes="72x72" href="{% static 'app/img/favicon/apple-touch-icon-72x72.png' %}">
	<link rel="apple-touch-icon" sizes="76x76" href="{% static 'app/img/favicon/apple-touch-icon-76x76.png' %}">
	<link rel="apple-touch-icon" sizes="114x114" href="{% static 'app/img/favicon/apple-touch-icon-114x114.png' %}">
	<link rel="apple-touch-icon" sizes="120x120" href="{% static 'app/img/favicon/apple-touch-icon-120x120.png' %}">
	<link rel="apple-touch-icon" sizes="144x144" href="{% static 'app/img/favicon/apple-touch-icon-144x144.png' %}">
	<link rel="apple-touch-icon" sizes="152x152" href="{% static 'app/img/favicon/apple-touch-icon-152x152.png' %}">
	<link rel="apple-touch-icon" sizes="180x180" href="{% static 'app/img/favicon/apple-touch-icon-180x180.png' %}">
	<link rel="icon" type="image/png" href="{% static 'app/img/favicon/favicon-32x32.png' %}" sizes="32x32">
	<link rel="icon" type="image/png" href="{% static 'app/img/favicon/android-chrome-192x192.png' %}" sizes="192x192">
	<link rel="icon" type="image/png" href="{% static 'app/img/favicon/favicon-96x96.png' %}" sizes="96x96">
	<link rel="icon" type="image/png" href="{% static 'app/img/favicon/favicon-16x16.png' %}" sizes="16x16">
	<link rel="manifest" href="{% static 'app/img/favicon/manifest.json' %}">
	<meta name="msapplication-TileColor" content="#da532c">
	<meta name="msapplication-TileImage" content="{% static 'app/img/favicon/mstile-144x144.png' %}">
	<meta name="theme-color" content="#ffffff">

	<!-- Google web fonts -->
	<link rel='stylesheet' href="http://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700" />
	<link rel='stylesheet' href="//fonts.googleapis.com/css?family=Raleway:400,300,600" type="text/css" />

	<!-- CSS styles -->
	<link rel="stylesheet" href="{% static 'app/css/libreeze.css' %}" />

	<script src="{% static 'app/js/vendor/modernizr-2.6.2.min.js' %}"></script>
</head>

<body>
	<!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

	<div class="container bodywrapper">
		<div class="row">
			<div class="column">
				<header>
					<a href="/"><img class="logo" src="{% static 'app/img/logo.png' %}" alt="libreeze" /></a>
					<nav>
						<ul>
							<li><a href="/support">support</a></li>
						</ul>
					</nav>
				</header>
				<div class="shadowbox verify-email-note">
				{% if verified_email %}
					<h2>Got it!</h2>
					<h6>Updates will be sent to <strong>{{ verified_email }}</strong>.</h6>
					<p>Thank you for relying on libreeze.net</p>

				{% elif unverified_email %}

					<h2>Got it!</h2>
					<h6>We have sent an email to <strong>{{ unverified_email }}</strong>. All you have to do now is confirm this is your email address.</h6>
					<p>Please check your inbox.</p>
				{% endif %}
				</div>
			</div>
		</div>
	</div>

	<footer class="text-center">
		<div class="container footerwrapper">
			<div class="row">
				<div class="column">
					&copy;libreeze 2015
				</div>
			</div>
		</div>
	</footer>

	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-61878758-1', 'auto');
		ga('send', 'pageview');
	</script>

</body>
</html>

app/templates/app/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

{% load staticfiles %}

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Libreeze</title>
	<meta name="description" content="">
	<meta name="author" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Favicons and apple-touch-icon.png -->
	<link rel="apple-touch-icon" sizes="57x57" href="{% static 'app/img/favicon/apple-touch-icon-57x57.png' %}">
	<link rel="apple-touch-icon" sizes="60x60" href="{% static 'app/img/favicon/apple-touch-icon-60x60.png' %}">
	<link rel="apple-touch-icon" sizes="72x72" href="{% static 'app/img/favicon/apple-touch-icon-72x72.png' %}">
	<link rel="apple-touch-icon" sizes="76x76" href="{% static 'app/img/favicon/apple-touch-icon-76x76.png' %}">
	<link rel="apple-touch-icon" sizes="114x114" href="{% static 'app/img/favicon/apple-touch-icon-114x114.png' %}">
	<link rel="apple-touch-icon" sizes="120x120" href="{% static 'app/img/favicon/apple-touch-icon-120x120.png' %}">
	<link rel="apple-touch-icon" sizes="144x144" href="{% static 'app/img/favicon/apple-touch-icon-144x144.png' %}">
	<link rel="apple-touch-icon" sizes="152x152" href="{% static 'app/img/favicon/apple-touch-icon-152x152.png' %}">
	<link rel="apple-touch-icon" sizes="180x180" href="{% static 'app/img/favicon/apple-touch-icon-180x180.png' %}">
	<link rel="icon" type="image/png" href="{% static 'app/img/favicon/favicon-32x32.png' %}" sizes="32x32">
	<link rel="icon" type="image/png" href="{% static 'app/img/favicon/android-chrome-192x192.png' %}" sizes="192x192">
	<link rel="icon" type="image/png" href="{% static 'app/img/favicon/favicon-96x96.png' %}" sizes="96x96">
	<link rel="icon" type="image/png" href="{% static 'app/img/favicon/favicon-16x16.png' %}" sizes="16x16">
	<link rel="manifest" href="{% static 'app/img/favicon/manifest.json' %}">
	<meta name="msapplication-TileColor" content="#da532c">
	<meta name="msapplication-TileImage" content="{% static 'app/img/favicon/mstile-144x144.png' %}">
	<meta name="theme-color" content="#ffffff">

	<!-- Google web fonts -->
	<link rel='stylesheet' href="http://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700" />
	<link rel='stylesheet' href="//fonts.googleapis.com/css?family=Raleway:400,300,600" type="text/css" />

	<!-- CSS styles -->
	<link rel="stylesheet" href="{% static 'app/css/libreeze.css' %}" />

	<script src="{% static 'app/js/vendor/modernizr-2.6.2.min.js' %}"></script>
</head>

<body>
	<!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

	<div class="container bodywrapper">
		<div class="row">
			<div class="column">
				<header>
					<a href="/"><img class="logo" src="{% static 'app/img/logo.png' %}" alt="libreeze" /></a>
					<nav>
						<ul>
							<li><a href="/support">support</a></li>
						</ul>
					</nav>

					<div class="lb-steps">
					<div>
						<div class="icon">
							<div class="pointerTop"></div>
							<div class="upload"></div>
						</div>
						<h1>Upload your <i>pom</i> file</h1>
						<span class="sub-text">don't worry, we do not scan anything except your project dependencies</span>
					</div>
					<div class="next-step">&#62;</div>
					<div>
						<div class="icon">
							<div class="tick"></div>
						</div>
						<h2>Check latest libraries</h2>
						<span class="sub-text">we'll find and display a list of latest available versions</span>
					</div>
					<div class="next-step">&#62;</div>
					<div>
						<div class="icon">
							<div class="letter"></div>
						</div>
						<h3>Leave your email</h3>
						<span class="sub-text">and we will send you a notification whenever a new version of your libraries is released</span>
					</div>
				</div>
				</header>

				<br/>

				<div id="lb-upload">
					<!-- conditionally set classes "lb-err", "lb-warn", "lb-success" to declare notification type and class "hidden" to toggle it's visibility -->
					{% if error %}
					<div class="notification lb-err">{{ error }}</div>
					{% endif %}

					<div class="shadowbox lb-upload-inner">
						<!-- Browse form -->
						<form id="upload-file" method="post" action="{% url 'app:submit_file' %}" enctype="multipart/form-data">
							<button class="browse-btn" type="button">Browse</button>
							<input type="file" name="pom-file" accept=".xml" />
							<button type="submit">Upload</button>
						</form>

						<span>- or -</span>

						<!-- Paste form -->
						<form id="upload-text" method="post" action="{% url 'app:submit_text' %}">
							<span class="lb-close toggle-upload-text"></span>
							<textarea name="pom-code"></textarea>
							<button type="submit">Upload</button>
						</form>
						<div>
							<button type="button" class="toggle-upload-text">Paste</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<footer class="text-center">
		<div class="container footerwrapper">
			<div class="row">
				<div class="column">
					&copy;libreeze 2015
				</div>
			</div>
		</div>
	</footer>

	<!-- JavaScript Includes -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<script>
		window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')
	</script>

	<!-- Our JS files -->
	<script src="{% static 'app/js/plugins.js' %}"></script>
	<script src="{% static 'app/js/lb-fileupload.js' %}"></script>

	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-61878758-1', 'auto');
		ga('send', 'pageview');
	</script>

</body>
</html>

app/templates/app/result.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

{% load staticfiles %}

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Libreeze</title>
	<meta name="description" content="">
	<meta name="author" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Favicons and apple-touch-icon.png -->
	<link rel="apple-touch-icon" sizes="57x57" href="{% static 'app/img/favicon/apple-touch-icon-57x57.png' %}">
	<link rel="apple-touch-icon" sizes="60x60" href="{% static 'app/img/favicon/apple-touch-icon-60x60.png' %}">
	<link rel="apple-touch-icon" sizes="72x72" href="{% static 'app/img/favicon/apple-touch-icon-72x72.png' %}">
	<link rel="apple-touch-icon" sizes="76x76" href="{% static 'app/img/favicon/apple-touch-icon-76x76.png' %}">
	<link rel="apple-touch-icon" sizes="114x114" href="{% static 'app/img/favicon/apple-touch-icon-114x114.png' %}">
	<link rel="apple-touch-icon" sizes="120x120" href="{% static 'app/img/favicon/apple-touch-icon-120x120.png' %}">
	<link rel="apple-touch-icon" sizes="144x144" href="{% static 'app/img/favicon/apple-touch-icon-144x144.png' %}">
	<link rel="apple-touch-icon" sizes="152x152" href="{% static 'app/img/favicon/apple-touch-icon-152x152.png' %}">
	<link rel="apple-touch-icon" sizes="180x180" href="{% static 'app/img/favicon/apple-touch-icon-180x180.png' %}">
	<link rel="icon" type="image/png" href="{% static 'app/img/favicon/favicon-32x32.png' %}" sizes="32x32">
	<link rel="icon" type="image/png" href="{% static 'app/img/favicon/android-chrome-192x192.png' %}" sizes="192x192">
	<link rel="icon" type="image/png" href="{% static 'app/img/favicon/favicon-96x96.png' %}" sizes="96x96">
	<link rel="icon" type="image/png" href="{% static 'app/img/favicon/favicon-16x16.png' %}" sizes="16x16">
	<link rel="manifest" href="{% static 'app/img/favicon/manifest.json' %}">
	<meta name="msapplication-TileColor" content="#da532c">
	<meta name="msapplication-TileImage" content="{% static 'app/img/favicon/mstile-144x144.png' %}">
	<meta name="theme-color" content="#ffffff">

	<!-- Google web fonts -->
	<link rel='stylesheet' href="http://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700" />
	<link rel='stylesheet' href="//fonts.googleapis.com/css?family=Raleway:400,300,600" type="text/css" />

	<!-- CSS styles -->
	<link rel="stylesheet" href="{% static 'app/css/libreeze.css' %}" />

	<script src="{% static 'app/js/vendor/modernizr-2.6.2.min.js' %}"></script>
</head>

<body class="project">
	<!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

	<div class="container bodywrapper">
		<div class="row">
			<header>
				<a href="/"><img class="logo" src="{% static 'app/img/logo.png' %}" alt="libreeze" /></a>
				<nav>
					<ul>
						<li><a href="support">support</a></li>
					</ul>
				</nav>
				<h1 class="project-name text-center">{{ project_name }}</h1>
			</header>

			<div class="contact-form">
				<!-- conditionally set classes "lb-err", "lb-warn", "lb-success" to declare notification type and class "hidden" to toggle it's visibility -->
				{% if error %}
				<div class="notification lb-err">{{ error }}</div>
				{% endif %}

				<form method="post" action="{% url 'app:submit_email' %}">
					<label for="email"><strong>Leave your email and get notified when new versions are released</strong></label>
					<input type="text" name="email" id="email"/>
					<button type="submit">Submit</button>
				</form>
			</div>
		</div>

		<div class="row">
			<div class="column">

				<table class="dep-table">
					<thead>
						<tr>
							<th>Group Id</th>
							<th>Artifact Id</th>
							<th>Your version</th>
							<th>Official</th>
							<th>Latest</th>
							<th>XML</th>
						</tr>
					</thead>
					<tbody>
						{% for dependency in dependencies %}
						<tr class="{% cycle 'odd' 'even' %}">
							<td data-th="Group Id">{{ dependency.group_id }}</td>
							<td data-th="Artifact Id">{{ dependency.artifact_id }}</td>
							<td data-th="Your version" class="version">
								{% if dependency.version %}
									{{ dependency.version }}
									{% if dependency.up_to_date %}
										<span class="lb-ico lb-ico-ok"></span>
									{% else %}
										<span class="lb-ico lb-ico-warn" title="Oops, out of date"></span>
									{% endif %}
								{% else %}
									<span class="lb-ico"></span>
									--
								{% endif %}
							</td>
							<td data-th="Official">
								{% if dependency.release %}
									{{ dependency.release }}
								{% else %}
									--
								{% endif %}
							</td>
							<td data-th="Latest">
								{% if dependency.latest %}
									{{ dependency.latest }}
								{% else %}
									--
								{% endif %}
							</td>
							<td data-th="XML" class="view-xml">
								<span class="lb-ico lb-ico-chevron" title="Click to view XML"></span>
							</td>
						</tr>
						<tr class="dependency-xml dependency-collapsed">
							<td colspan="6">
								<div>
									<ul class="xml-acts">
										<li class="copy-xml" data-clipboard-target="clipboard-text" title="Click to copy xml"><b>copy xml</b></li>
									</ul>
									<!-- Textarea preserves indentation so please do not indent it's value -->
									<textarea readonly class="xml_result" name="clipboard-text" id="clipboard-text">
<dependency>
	<groupId>{{ dependency.group_id }}</groupId>
	<artifactId>{{ dependency.artifact_id }}</artifactId>
	<version>{% if dependency.release %}{{ dependency.release }}{% elif dependency.latest %}{{ dependency.latest }}{% else %}{{ dependency.version }}{% endif %}</version>
</dependency></textarea>
								</div>
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<footer class="text-center">
		<div class="container footerwrapper">
			<div class="row">
				<div class="column">
					&copy;libreeze 2015
				</div>
			</div>
		</div>
	</footer>

	<!-- JavaScript Includes -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<script>
		window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')
	</script>

	<!-- Copy to clipboard JS -->
	<script src="{% static 'app/js/zeroclipboard/ZeroClipboard.js' %}"></script>

	<!-- Our JS files -->
	<script src="{% static 'app/js/plugins.js' %}"></script>
	<script src="{% static 'app/js/lb-result.js' %}"></script>

	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-61878758-1', 'auto');
		ga('send', 'pageview');
	</script>

</body>
</html>